### ISSUE TITLE
`Seat`s cannot log opening of seats

### ISSUE THREAD

**Issue by StripedMonkey** [PolyMeilex/libseat-rs#6]
Currently `Seat::open` will create a log handler, but only after `libseat_open_seat()` is called and returns a seat, making it impossible to log failing to open a seat properly. Additionally, while `LogHandler` itself is pub, the module `log_handler` itself is not, making it inaccessible to construct yourself (not that you'd want *two* log handlers).

**Comment by PolyMeilex** [comment]
> Currently Seat::open will create a log handler, but only after libseat_open_seat() is called and returns a seat, making it impossible to log failing to open a seat properly

This is not true as far as I can tell.

**Comment by StripedMonkey** [comment]
Maybe I'm misinterpreting things then, How are you able to set the log level prior to constructing a seat with `Seat::open`.

**Comment by PolyMeilex** [comment]
Log level is not associated with seats, it's just a global variable on the C side.

That being said currently you can't set it prior to seat open because we set it to Debug (aka. All logs) in the log handler constructor, as I expect people that opted into rust log handler to just filter unnesecary logs on the rust side.

If you don't use rust logs, then you can set the log level whenever and it is not overritem anywhere.

Better question would be, what are you trying to do?

**Comment by PolyMeilex** [comment]
![image](https://github.com/PolyMeilex/libseat-rs/assets/20758186/9245142e-e7c2-40a8-a679-718b2d11c54d)

This looks like a full log to me (I used env_logger here), am I missing something?

**Comment by StripedMonkey** [comment]
Maybe the issue here is further up the chain for me, I'm currently in the midst of debugging cosmic-epoch, and was not seeing any libseat messages, and stepping through seemed to yield a "not implemented" error via libseat without any logging despite me enabling the feature and setting the log level. Since this is apparently a more upstream issue I'll close this.
